server:
  port: 8085
hm:
  db:
    database: hm-trade
  swagger:
    title: "trade api"
    package: com.hmall.trade.controller
spring:
  rabbitmq:
    host: "***" # IP
    port: 5672 # port
    virtual-host: "***" # host name
    username: "***" # username
    password: "***" # pswd
